export type Pick = {
  name: string;
  category: string;
  badge: string;
  tried?: boolean;
  tagline: string;
  description: string[];
  listLabel: string;
  highlights: string[];
  note?: string;
  specs: string[];
  affiliateUrl: string;
  resolvedProductUrl: string | null;
  imageUrl: string;
};

// Product copy, destinations, and local imagery are centralized here for easy editing.
export const picks: Pick[] = [
  {
    name: "GEEKOM AX8 Max",
    category: "Mini PC",
    badge: "Best Balanced Mini PC",
    tagline: "أفضل Mini PC متوازن للوكلاء والتشغيل المحلي",
    description: [
      "مناسب لمن يريد جهازًا صغيرًا وقويًا لتشغيل الوكلاء، الأتمتة، Docker، الخدمات المحلية، البرمجة وتعدد المهام مع إمكانية تشغيل نماذج AI محلية خفيفة إلى متوسطة.",
      "يأتي بمعالج AMD Ryzen 7 8745HS وذاكرة 32GB DDR5 وقرص 1TB NVMe، إضافة إلى Radeon 780M الذي يمنحه أداء رسوميًا أفضل من أغلب أجهزة Mini PC المكتبية التقليدية.",
    ],
    listLabel: "اختره إذا كنت تحتاج:",
    highlights: ["AI Agents وأتمتة تعمل محليًا", "Docker وحاويات متعددة", "Local Servers وواجهات API", "تشغيل نماذج LLM صغيرة ومتوسطة محليًا", "أكثر من شاشة QHD أو 4K", "تحرير صور وفيديو خفيف و3D بسيط", "جهاز صغير يمكن تشغيله لساعات طويلة"],
    note: "ليس الخيار الأفضل إذا كان هدفك الرئيسي تدريب نماذج AI كبيرة أو 3D ورندر ثقيل؛ وقتها تحتاج جهازًا بكرت NVIDIA RTX منفصل.",
    specs: ["Ryzen 7 8745HS", "32GB DDR5", "1TB NVMe SSD", "Radeon 780M", "USB4 40Gbps", "Dual 2.5GbE", "Windows 11 Pro"],
    affiliateUrl: "https://link.amazon/B0eEu07xI",
    resolvedProductUrl: "https://www.geekompc.com/product/geekom-ax8-max-mini-pc/",
    imageUrl: "/picks/geekom-ax8-max.webp",
  },
  {
    name: "GEEKOM IT13",
    category: "Mini PC",
    badge: "CPU & Storage Pick",
    tagline: "Mini PC قوي للبرمجة والخوادم وتعدد الخدمات",
    description: ["خيار مناسب لمن تكون أولويته قوة المعالج والتخزين الكبير أكثر من الأداء الرسومي. مع Intel Core i9-13900H و32GB RAM و2TB SSD، يناسب بيئات التطوير، قواعد البيانات، الخوادم المحلية، الأجهزة الافتراضية والخدمات التي تعمل بالتوازي."],
    listLabel: "اختره إذا كنت تحتاج:",
    highlights: ["برمجة ومشاريع تطوير كبيرة", "Docker وVMs متعددة", "قواعد بيانات محلية", "تشغيل خوادم وأتمتة على مدار اليوم", "2TB تخزين من البداية", "تعدد مهام يعتمد أكثر على CPU من GPU", "عدة شاشات للعمل والإنتاجية"],
    note: "ليس الخيار الأفضل إذا كان شغلك يعتمد على الرسوميات، 3D أو نماذج AI التي تستفيد من GPU؛ Intel Iris Xe أضعف من Radeon 780M الموجود في AX8 Max.",
    specs: ["Intel Core i9-13900H", "32GB RAM", "2TB SSD", "Intel Iris Xe", "Windows 11 Pro"],
    affiliateUrl: "https://link.amazon/B08ZW4xGb",
    resolvedProductUrl: "https://www.geekompc.com/geekom-it13-mini-pc/",
    imageUrl: "/picks/geekom-it13.webp",
  },
  {
    name: "Acer Aspire Go 15",
    category: "Laptops",
    badge: "Work & Coding Pick",
    tagline: "لابتوب مناسب للبرمجة والتجارة الإلكترونية والعمل اليومي",
    description: ["اختيار عملي لمن يحتاج جهازًا متنقلًا بذاكرة كبيرة وتخزين كافٍ للبرمجة، إدارة المتاجر الإلكترونية، الدراسة والعمل المكتبي وتعدد المهام.", "ذاكرة 32GB تجعله مناسبًا لمن يفتح عددًا كبيرًا من البرامج والتبويبات في وقت واحد، بينما يوفر 1TB SSD مساحة جيدة للمشاريع والملفات."],
    listLabel: "اختره إذا كنت تحتاج:",
    highlights: ["برمجة وتطوير ويب", "إدارة متجر إلكتروني", "أدوات SaaS وCRM", "متصفح مع عدد كبير من التبويبات", "VS Code وأدوات التطوير", "أعمال مكتبية ودراسة", "جهاز متنقل أكثر من Mini PC"],
    note: "ليس الخيار الأفضل إذا كنت تعمل على 3D أو مونتاج ثقيل أو AI محلي يعتمد على GPU؛ لا يحتوي على RTX منفصل.",
    specs: ["AMD Ryzen 7 5825U", "32GB RAM", "1TB SSD", "شاشة 15.6 بوصة FHD IPS"],
    affiliateUrl: "https://link.amazon/B0esddtNw",
    resolvedProductUrl: "https://www.acer.com/de-de/laptops/aspire/aspire-go-amd/pdp/NX.J7XEV.001",
    imageUrl: "/picks/acer-aspire-go-15.jpg",
  },
  {
    name: "Acer Nitro V",
    category: "Laptops",
    badge: "Power Pick — 3D & AI",
    tagline: "لابتوب قوي للـ3D والذكاء الاصطناعي والمونتاج",
    description: ["مناسب لمن يحتاج جهازًا متنقلًا يجمع بين معالج قوي وكرت شاشة NVIDIA RTX للعمل على Blender، التصميم ثلاثي الأبعاد، المونتاج وتطبيقات الذكاء الاصطناعي التي تستفيد من CUDA.", "وجود RTX 5060 يجعل الفرق كبيرًا مقارنة باللابتوبات التي تعتمد على الرسوميات المدمجة فقط."],
    listLabel: "اختره إذا كنت تحتاج:",
    highlights: ["Blender و3D", "Adobe Premiere وDaVinci Resolve", "Stable Diffusion وتطبيقات AI محلية", "CUDA وMachine Learning", "تصميم ورندر", "ألعاب وأعمال رسومية ثقيلة", "جهاز قوي يمكن نقله"],
    note: "16GB RAM مناسبة كبداية، لكن 32GB أفضل إذا كان شغلك ثقيلًا أو تستخدم نماذج AI و3D باستمرار.",
    specs: ["Intel Core i9-13900H", "NVIDIA RTX 5060", "16GB RAM", "1TB SSD", "شاشة 15.6 بوصة FHD IPS 165Hz"],
    affiliateUrl: "https://link.amazon/B0fObgluZ",
    resolvedProductUrl: "https://store.acer.com/en-ie/acer-nitro-v-15-gaming-laptop-anv15-52-black-nh-qzaek-00a",
    imageUrl: "/picks/acer-nitro-v.jpg",
  },
  {
    name: "KTC 27-inch QHD",
    category: "Monitors",
    badge: "Best Value",
    tagline: "شاشة QHD اقتصادية للبرمجة والعمل",
    description: ["خيار اقتصادي ممتاز لمن يريد الانتقال من Full HD إلى QHD بدون رفع الميزانية كثيرًا. دقة 2560×1440 على مقاس 27 بوصة تعطي مساحة عمل أكبر ووضوحًا أفضل للنصوص والنوافذ."],
    listLabel: "مناسبة لـ:",
    highlights: ["البرمجة وVS Code", "التجارة الإلكترونية", "العمل المكتبي", "تعدد النوافذ", "الدراسة", "الاستخدام اليومي"],
    note: "اخترها إذا كان هدفك أفضل قيمة مقابل السعر ولا تحتاج 200Hz أو مزايا Gaming متقدمة.",
    specs: ["27 بوصة", "QHD 2560×1440", "IPS", "100Hz"],
    affiliateUrl: "https://link.amazon/B0e5nBPQG",
    resolvedProductUrl: "https://us.ktcplay.com/products/24-2k-100hz-office-monitor",
    imageUrl: "/picks/ktc-qhd-monitor.png",
  },
  {
    name: "BenQ EW270Q",
    category: "Monitors",
    badge: "Best Overall",
    tagline: "أفضل شاشة متوازنة للعمل وصناعة المحتوى",
    description: ["مناسبة للبرمجة، تعدد النوافذ، أجهزة Mini PC وDesktop وصناعة المحتوى. معدل التحديث 200Hz يوفر تجربة عرض سلسة، وUSB-C 65W ميزة إضافية لمن يريد توصيل لابتوب أيضًا."],
    listLabel: "مناسبة لـ:",
    highlights: ["البرمجة والعمل المكتبي", "صناعة المحتوى", "تحرير الصور والفيديو", "الأجهزة المزودة بـUSB-C", "الألعاب الخفيفة والمتوسطة", "تعدد المهام"],
    note: "اخترها إذا كنت تريد شاشة واحدة متوازنة للعمل والترفيه بدون الوصول لأسعار الشاشات الاحترافية الأعلى.",
    specs: ["27 بوصة", "QHD", "IPS", "200Hz", "USB-C 65W", "HDRi", "FreeSync Premium"],
    affiliateUrl: "https://link.amazon/B0eTnqxDF",
    resolvedProductUrl: "https://www.benq.eu/en-uk/monitor/home/ew270q.html",
    imageUrl: "/picks/benq-ew270q.jpg",
  },
  {
    name: "LG UltraGear 27G610A-B",
    category: "Monitors",
    badge: "Premium Display Pick",
    tagline: "شاشة QHD قوية للألعاب والمحتوى البصري",
    description: ["مناسبة لمن يهتم بالحركة السلسة والأداء البصري أكثر من مجرد الاستخدام المكتبي. معدل 200Hz ووقت الاستجابة السريع يجعلانها مناسبة للألعاب، الفيديو والحركة السريعة."],
    listLabel: "مناسبة لـ:",
    highlights: ["Gaming", "تحرير الفيديو", "صناعة المحتوى", "شغل بصري سريع", "تعدد الاستخدامات", "من يريد حاملًا قابلًا للتعديل وHDR أفضل"],
    note: "اخترها إذا كنت تفضل علامة تجارية معروفة وتجربة Display أقوى، ولا تمانع دفع سعر أعلى من شاشات العمل الأساسية.",
    specs: ["27 بوصة", "QHD 2560×1440", "IPS", "200Hz", "1ms", "HDR400", "FreeSync Premium"],
    affiliateUrl: "https://link.amazon/B01Lawz8O",
    resolvedProductUrl: null,
    imageUrl: "/picks/lg-ultragear-27g610a-b.jpg",
  },
  {
    name: "Monitor Arm",
    category: "Monitor Arm",
    badge: "مجرّب في نوسج",
    tried: true,
    tagline: "حامل شاشة مجرّب في نوسج",
    description: ["حامل شاشة عملي يساعد على توفير مساحة المكتب وتحسين وضعية الشاشة وتنظيم بيئة العمل.", "هذا المنتج مستخدم فعليًا في نوسج، وهو مناسب لمن يريد تحرير مساحة المكتب ورفع الشاشة إلى مستوى أكثر راحة."],
    listLabel: "مناسب لـ:",
    highlights: ["مكاتب البرمجة", "شاشات 27 بوصة", "تنظيم الكابلات", "تحسين وضعية الجلوس", "تجهيزات العمل متعددة الشاشات"],
    note: "ميزة هذا الاختيار: منتج مجرّب فعليًا وليس مجرد توصية مبنية على المواصفات.",
    specs: [],
    affiliateUrl: "https://link.amazon/B04kDNUFZ",
    resolvedProductUrl: null,
    imageUrl: "/picks/monitor-arm.jpg",
  },
  {
    name: "Newline 4K AI Webcam",
    category: "AI Webcam",
    badge: "AI Webcam Pick",
    tagline: "كاميرا 4K بميزات AI للاجتماعات والتتبع",
    description: ["كاميرا مناسبة لمن يريد أكثر من Webcam تقليدية. تدعم ميزات ذكاء اصطناعي مثل Auto Framing وتتبع المتحدث والتحكم بالإيماءات، مما يجعلها مناسبة للاجتماعات، البث، صناعة المحتوى وبعض تطبيقات الرؤية الحاسوبية البسيطة."],
    listLabel: "مناسبة لـ:",
    highlights: ["اجتماعات Zoom وTeams", "صناعة المحتوى", "البث المباشر", "Auto Framing", "Speaker Tracking", "Gesture Control", "استخدامات AI Vision الخفيفة", "التسجيل بدقة 4K"],
    specs: ["4K UHD", "Auto Framing", "Speaker Tracking", "AI Zoom", "Gesture Control", "Autofocus", "عدة زوايا FOV", "ميكروفون مع تقليل ضوضاء", "Privacy Cover"],
    affiliateUrl: "https://link.amazon/B0160xagn",
    resolvedProductUrl: null,
    imageUrl: "/picks/newline-4k-ai-webcam.jpg",
  },
  {
    name: "Thunder Rift AI / 3D Desktop",
    category: "Desktop / Workstation",
    badge: "High-End AI & 3D Pick",
    tagline: "محطة عمل قوية للذكاء الاصطناعي المحلي والـ3D",
    description: ["هذا هو الخيار الأقوى في القائمة لمن يحتاج جهازًا مكتبيًا حقيقيًا لتشغيل نماذج AI محلية، العمل على 3D والرندر والمونتاج والأحمال التي تعتمد على GPU.", "RTX 5070 بذاكرة 12GB VRAM يعطيه أفضلية واضحة على Mini PC واللابتوبات ذات الرسوميات المدمجة، ويجعله مناسبًا لتطبيقات CUDA، Stable Diffusion، الرندر وبعض نماذج LLM المحلية."],
    listLabel: "اختره إذا كنت تحتاج:",
    highlights: ["Local AI وLLMs", "AI Agents تعتمد على نماذج محلية", "Stable Diffusion", "Blender و3D Rendering", "CUDA", "مونتاج فيديو ثقيل", "Gaming عالي الأداء", "تشغيل طويل مع قابلية ترقية مستقبلية"],
    note: "إذا كان استخدامك فقط برمجة، تجارة إلكترونية وأتمتة تعتمد على APIs، فالـMini PC أوفر بكثير ولن تحتاج قوة هذه التجميعة.",
    specs: ["AMD Ryzen 7 7800X3D", "NVIDIA RTX 5070 12GB", "32GB DDR5 6000MHz", "2TB Gen4 NVMe SSD", "AIO Liquid Cooling", "Windows 11 Pro"],
    affiliateUrl: "https://link.amazon/B02qmPFwz",
    resolvedProductUrl: null,
    imageUrl: "/picks/thunder-rift-gaming-ai-desktop.jpg",
  },
];
