const shared={generalEmail:"info@nawwsaj.com",partnershipsEmail:"partnerships@nawwsaj.com",website:"nawwsaj.com"};
export const siteContent={
 en:{lang:"en",dir:"ltr",nav:[{label:"Product",href:"#product"},{label:"Lab",href:"#lab"},{label:"Contact",href:"#contact"}],headerCta:"Contact",statusLine:"FUNCTIONAL MVP · ACTIVE DEVELOPMENT",hero:{headline:"An intelligent operating system for innovation environments.",supporting:"AI agents, connected devices, automation, and interactive tools — unified in one workspace.",primary:"Explore Nawwsaj OS",secondary:"Inside the Lab",foot:["AI AGENTS","CONNECTED DEVICES","INTERACTIVE TOOLS"]},
 intro:{label:"01 / THE SYSTEM",title:"From Idea to Working Prototype",copy:"Nawwsaj OS is being developed as an intelligent operating layer for innovation environments. It brings together AI agents, project context, connected devices, automation, and interactive interfaces to help move ideas through a practical development cycle.",process:["Idea","Decision","Execution","Testable MVP"],goal:"The goal is to reduce friction between thinking, building, testing, and managing innovation projects."},
 core:{label:"02 / CORE SYSTEM",titleA:"One workspace.",titleB:"Four connected layers.",items:[{icon:"✦",title:"AI Agents",description:"AI agents assist with ideation, planning, analysis, project support, and execution."},{icon:"⌁",title:"Connected Lab Devices",description:"A unified layer for coordinating IoT devices, electronics, and physical systems inside the innovation environment."},{icon:"◎",title:"Interactive Interfaces",description:"Vision, gesture interaction, projection, and responsive interfaces designed for hands-on experimentation."},{icon:"◇",title:"Project Memory & Automation",description:"Persistent project context and automated workflows designed to keep projects, experiments, and development organized."}]},
 spatial:{label:"03 / REAL PRODUCT INTERFACE",title:"Nawwsaj Spatial Home",description:"The central interface of Nawwsaj OS, designed to organize agents, workspaces, conversations, settings, and interactive tools inside one innovation environment.",open:"OPEN FULL SIZE ↗"},
 workbench:{label:"04 / PHYSICAL × DIGITAL",title:"Interactive Workbench",description:"A vision-enabled workspace designed for object scanning, gesture interaction, and hands-on experimentation. It connects physical prototyping with digital workflows inside Nawwsaj OS.",supporting:"The workspace uses a camera-based interaction layer to create a physical-digital experimentation area where users can scan objects, navigate tools, and interact with the system using gestures.",status:"IN ACTIVE DEVELOPMENT"},
 environment:{label:"05 / BEYOND SOFTWARE",title:"Connected Innovation Environment",intro:"Nawwsaj OS goes beyond software. The surrounding innovation environment can become part of the system itself.",diagram:["AI / SOFTWARE","NAWWSAJ OS","CONNECTED DEVICES","PHYSICAL ENVIRONMENT"],features:[{title:"Interactive Workbench",description:"A camera-guided and gesture-aware workspace that connects hands-on experimentation with digital tools."},{title:"Ambient Control",description:"Lighting and audio can respond to working contexts and support focus, exploration, presentation, or celebration."},{title:"Connected Device Actions",description:"Selected physical devices can connect to Nawwsaj OS, allowing software workflows to trigger real-world actions and routines.",examples:["Smart lighting","Audio","IoT devices","Lab equipment","Selected automated routines"]}],statement:"The lab itself becomes responsive to the workflow."},
 uses:{label:"06 / USE CASES",title:"Built for Innovation Environments",intro:"Nawwsaj OS explores how innovation spaces can become more intelligent, connected, and responsive. These are target use cases and future deployment possibilities.",items:["Managing innovation projects","Assisting teams through AI agents","Connecting lab equipment and IoT devices","Supporting rapid prototyping workflows","Creating interactive learning experiences","Organizing project knowledge and progress","Supporting hands-on experimentation","Integrating digital and physical environments"]},
 lab:{label:"07 / NAWWSAJ LAB",title:"Built Inside a Real Innovation Lab",copy:"Nawwsaj OS is not being designed only as a software concept. Its components are being developed and tested inside Nawwsaj Lab, where software, AI, electronics, connected devices, and interaction design are brought together in one experimental environment.",captionA:"System interface / Nawwsaj OS",captionB:"Prototype / Interactive Workbench"},
 builds:{label:"08 / SELECTED BUILDS",title:"Systems in development",intro:"Real components developed through Nawwsaj Lab.",items:[{title:"Nawwsaj OS",description:"Unified system for AI agents, project workflows, connected devices, and interactive innovation environments.",status:"FUNCTIONAL MVP — ACTIVE DEVELOPMENT"},{title:"AI Agent Management",description:"A system for coordinating specialized AI agents and connecting them to project workflows."},{title:"Interactive Workbench",description:"Computer-vision and gesture-based interface connecting physical experimentation with digital tools."},{title:"IoT Lab Control",description:"Connected-device infrastructure for controlling and coordinating physical systems inside the lab."},{title:"Robotics & Electronics Prototypes",description:"Hands-on prototypes combining software, electronics, robotics, sensors, and rapid experimentation."}]},
 builder:{label:"09 / BUILDER PROFILE",title:"Built by Afnan AlDuhaim",primary:"Computer Science graduate and innovation-focused technology developer with nearly three years of experience training teams in robotics, electronics, IoT, and digital prototyping. Her work focuses on turning ideas into functional prototypes and integrating emerging technologies into practical innovation environments.",secondary:"She currently develops AI-powered systems, automation workflows, interactive interfaces, and connected-device experiences through Nawwsaj Lab."},
 achievements:{title:"INNOVATION & COMPETITION EXPERIENCE",items:[{place:"1st Place — Saudi Arabia",event:"Codeavour 2025"},{place:"Bronze Medal — Global",event:"Codeavour 2025"},{place:"Special Award — Global",event:"GRC 2025"},{place:"2nd Place — Saudi Arabia",event:"WRO 2024"},{place:"3rd Place — Saudi Arabia",event:"WRO 2025"},{place:"3rd Place",event:"ELO 2024 · Community Service Track"}],note:"Experience includes coaching teams from early concept development through prototyping, testing, presentation, and national and international competition readiness."},
 current:{label:"10 / CURRENT STATUS",main:"Functional MVP",secondary:"Active Development",description:"Core components have been built and tested inside Nawwsaj Lab. System integration, interaction design, AI capabilities, and connected-device workflows continue to evolve toward broader deployment."},vision:{label:"11 / THE VISION",statement:"To create innovation environments where AI, people, software, and physical tools work together as one connected system — making it easier to move from curiosity to experimentation, and from idea to working prototype."},contact:{label:"12 / CONNECT",titleA:"Build. Experiment.",titleB:"Connect.",supporting:"For innovation programs, partnerships, incubation, and technology opportunities.",primaryCta:"Contact Nawwsaj",primaryHref:"mailto:info@nawwsaj.com?subject=Nawwsaj%20Inquiry",secondaryCta:"Partnerships & Innovation Centers",secondaryHref:"mailto:partnerships@nawwsaj.com?subject=Partnership%20%2F%20Innovation%20Center%20Inquiry",...shared},footer:{back:"BACK TO TOP ↑",copyright:"© 2026 Nawwsaj Lab"}},
 ar:{lang:"ar",dir:"rtl",nav:[{label:"المنتج",href:"#product"},{label:"المعمل",href:"#lab"},{label:"تواصل",href:"#contact"}],headerCta:"تواصل",statusLine:"نموذج أولي وظيفي • قيد التطوير",hero:{headline:"نظام تشغيل ذكي للبيئات الابتكارية",supporting:"وكلاء ذكاء اصطناعي، أجهزة متصلة، أتمتة وأدوات تفاعلية — ضمن مساحة عمل واحدة.",primary:"استكشف Nawwsaj OS",secondary:"داخل المعمل",foot:["وكلاء AI","أجهزة متصلة","أدوات تفاعلية"]},
 intro:{label:"01 / النظام",title:"من الفكرة إلى نموذج أولي يعمل",copy:"يتم تطوير Nawwsaj OS كطبقة تشغيل ذكية للبيئات الابتكارية، تجمع بين وكلاء الذكاء الاصطناعي، سياق المشروع، الأجهزة المتصلة، الأتمتة والواجهات التفاعلية، للمساعدة في نقل الأفكار عبر دورة تطوير عملية.",process:["فكرة","قرار","تنفيذ","نموذج أولي قابل للاختبار"],goal:"الهدف هو تقليل الفجوة بين التفكير، البناء، الاختبار وإدارة المشاريع الابتكارية."},
 core:{label:"02 / النظام الأساسي",titleA:"مساحة عمل واحدة.",titleB:"أربع طبقات مترابطة.",items:[{icon:"✦",title:"وكلاء الذكاء الاصطناعي",description:"وكلاء متخصصون يدعمون توليد الأفكار، التخطيط، التحليل، متابعة المشاريع والتنفيذ."},{icon:"⌁",title:"أجهزة المعمل المتصلة",description:"طبقة موحدة لربط وتنسيق أجهزة IoT والإلكترونيات والأنظمة المادية داخل البيئة الابتكارية."},{icon:"◎",title:"واجهات تفاعلية",description:"رؤية حاسوبية، تفاعل بالإيماءات، إسقاط وواجهات متجاوبة مصممة للتجارب العملية."},{icon:"◇",title:"ذاكرة المشاريع والأتمتة",description:"سياق مستمر للمشاريع وسير عمل مؤتمت يساعد على تنظيم التجارب والتطوير والمعرفة المتراكمة."}]},
 spatial:{label:"03 / واجهة المنتج الحقيقية",title:"Nawwsaj Spatial Home",description:"الواجهة المركزية في Nawwsaj OS لتنظيم الوكلاء، مساحات العمل، المحادثات، الإعدادات والأدوات التفاعلية ضمن بيئة ابتكارية موحدة.",open:"فتح بالحجم الكامل ↖"},
 workbench:{label:"04 / المادي × الرقمي",title:"Interactive Workbench",description:"مساحة عمل مدعومة بالرؤية الحاسوبية، مصممة لمسح العناصر، التفاعل بالإيماءات والتجريب العملي، بحيث تربط النمذجة المادية بسير العمل الرقمي داخل Nawwsaj OS.",supporting:"تستخدم مساحة العمل طبقة تفاعل معتمدة على الكاميرا لإنشاء منطقة تجريب مادية-رقمية، يستطيع المستخدم من خلالها مسح العناصر، التنقل بين الأدوات والتفاعل مع النظام باستخدام الإيماءات.",status:"قيد التطوير النشط"},
 environment:{label:"05 / ما بعد البرمجيات",title:"بيئة ابتكارية متصلة",intro:"يتجاوز Nawwsaj OS حدود البرمجيات، بحيث يمكن أن تصبح البيئة الابتكارية المحيطة جزءًا من النظام نفسه.",diagram:["AI / البرمجيات","NAWWSAJ OS","الأجهزة المتصلة","البيئة المادية"],features:[{title:"Interactive Workbench",description:"مساحة عمل تعتمد على الكاميرا والإيماءات لربط التجريب العملي بالأدوات الرقمية."},{title:"التحكم في أجواء البيئة",description:"يمكن للإضاءة والصوت الاستجابة لسياق العمل ودعم أوضاع مثل التركيز، الاستكشاف، العرض أو الاحتفال."},{title:"تنفيذ الأوامر عبر الأجهزة المتصلة",description:"يمكن ربط أجهزة مادية مختارة بـ Nawwsaj OS، بما يسمح لسير العمل البرمجي بتشغيل إجراءات وروتينات في العالم الحقيقي.",examples:["إضاءة ذكية","صوت","أجهزة IoT","معدات المعمل","روتينات مؤتمتة مختارة"]}],statement:"المعمل نفسه يصبح جزءًا متفاعلًا مع سير العمل."},
 uses:{label:"06 / حالات الاستخدام",title:"مصمم للبيئات الابتكارية",intro:"يستكشف Nawwsaj OS كيف يمكن لمساحات الابتكار أن تصبح أكثر ذكاءً وترابطًا واستجابة. تُعرض هذه كحالات استخدام مستهدفة وإمكانات مستقبلية للتطبيق.",items:["إدارة المشاريع الابتكارية","دعم الفرق عبر وكلاء الذكاء الاصطناعي","ربط أجهزة المعمل وأجهزة IoT","دعم تطوير النماذج الأولية بسرعة","إنشاء تجارب تعلم تفاعلية","تنظيم معرفة المشاريع وتقدمها","دعم التجارب العملية","دمج البيئات الرقمية والمادية"]},
 lab:{label:"07 / معمل Nawwsaj",title:"يُبنى داخل معمل ابتكار حقيقي",copy:"لا يتم تصميم Nawwsaj OS كمفهوم برمجي فقط، بل يتم تطوير مكوناته واختبارها داخل Nawwsaj Lab، حيث تجتمع البرمجيات والذكاء الاصطناعي والإلكترونيات والأجهزة المتصلة وتصميم التفاعل ضمن بيئة تجريبية واحدة.",captionA:"واجهة النظام / Nawwsaj OS",captionB:"نموذج أولي / Interactive Workbench"},
 builds:{label:"08 / أنظمة مختارة",title:"أنظمة قيد التطوير",intro:"مكونات حقيقية يتم تطويرها من خلال Nawwsaj Lab.",items:[{title:"Nawwsaj OS",description:"نظام موحد لوكلاء الذكاء الاصطناعي، سير عمل المشاريع، الأجهزة المتصلة والبيئات الابتكارية التفاعلية.",status:"نموذج أولي وظيفي — قيد التطوير"},{title:"إدارة وكلاء الذكاء الاصطناعي",description:"نظام لتنسيق وكلاء ذكاء اصطناعي متخصصين وربطهم بسير عمل المشاريع."},{title:"Interactive Workbench",description:"واجهة تعتمد على الرؤية الحاسوبية والإيماءات لربط التجريب المادي بالأدوات الرقمية."},{title:"التحكم بأجهزة المعمل عبر IoT",description:"بنية للأجهزة المتصلة تهدف إلى التحكم في الأنظمة المادية داخل المعمل وتنسيقها."},{title:"نماذج أولية في الروبوتات والإلكترونيات",description:"نماذج عملية تجمع بين البرمجيات، الإلكترونيات، الروبوتات، الحساسات والتجريب السريع."}]},
 builder:{label:"09 / الملف المهني",title:"بُني بواسطة أفنان الدحيم",primary:"خريجة علوم حاسب ومطورة تقنية تركز على الابتكار، بخبرة تقارب ثلاث سنوات في تدريب فرق الروبوتات والإلكترونيات وإنترنت الأشياء وبناء النماذج الأولية الرقمية. يتركز عملها على تحويل الأفكار إلى نماذج قابلة للتطبيق ودمج التقنيات الحديثة داخل بيئات ابتكارية عملية.",secondary:"تعمل حاليًا على تطوير أنظمة تعتمد على الذكاء الاصطناعي، الأتمتة، الواجهات التفاعلية وتجارب الأجهزة المتصلة من خلال Nawwsaj Lab."},
 achievements:{title:"خبرة في الابتكار والمسابقات",items:[{place:"المركز الأول — السعودية",event:"Codeavour 2025"},{place:"الميدالية البرونزية — عالمي",event:"Codeavour 2025"},{place:"جائزة خاصة — عالمي",event:"GRC 2025"},{place:"المركز الثاني — السعودية",event:"WRO 2024"},{place:"المركز الثالث — السعودية",event:"WRO 2025"},{place:"المركز الثالث",event:"ELO 2024 · مسار الخدمة المجتمعية"}],note:"تشمل الخبرة تدريب الفرق منذ تطوير الفكرة الأولى، مرورًا ببناء النموذج الأولي والاختبار والعرض، وصولًا إلى الاستعداد للمنافسات المحلية والدولية."},
 current:{label:"10 / الحالة الحالية",main:"نموذج أولي وظيفي",secondary:"قيد التطوير النشط",description:"تم بناء واختبار المكونات الأساسية داخل Nawwsaj Lab. ويستمر تطوير تكامل النظام، تصميم التفاعل، قدرات الذكاء الاصطناعي وسير عمل الأجهزة المتصلة استعدادًا لتوسيع نطاق الاستخدام مستقبلًا."},vision:{label:"11 / الرؤية",statement:"إنشاء بيئات ابتكارية يعمل فيها الذكاء الاصطناعي والإنسان والبرمجيات والأدوات المادية كنظام واحد مترابط — لتسهيل الانتقال من الفضول إلى التجريب، ومن الفكرة إلى نموذج أولي يعمل."},contact:{label:"12 / تواصل",titleA:"ابنِ. جرّب.",titleB:"تواصل.",supporting:"للبرامج الابتكارية، الشراكات، الاحتضان والفرص التقنية.",primaryCta:"تواصل مع Nawwsaj",primaryHref:"mailto:info@nawwsaj.com?subject=Nawwsaj%20Inquiry",secondaryCta:"الشراكات ومراكز الابتكار",secondaryHref:"mailto:partnerships@nawwsaj.com?subject=Partnership%20%2F%20Innovation%20Center%20Inquiry",...shared},footer:{back:"العودة للأعلى ↑",copyright:"© 2026 Nawwsaj Lab"}}
} as const;
export type Language=keyof typeof siteContent;
