import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Suhail سهيل | اتصال LoRa وأنظمة Edge ميدانية",
  description: "سهيل مشروع هندسي قيد التطوير داخل Nawwsaj Lab لاتصال ميداني يعمل في البيئات ذات الاتصال الضعيف أو المنقطع باستخدام LoRa وEdge وEmbedded Systems.",
  alternates: { canonical: "/projects/suhail" },
  robots: { index: true, follow: true },
  openGraph: { title: "Suhail سهيل | Built inside Nawwsaj Lab", description: "مشروع اتصال ميداني يجمع LoRa والأنظمة المضمنة والمعالجة الطرفية، قيد التطوير والاختبار داخل المعمل.", url: "/projects/suhail", type: "article", images: [{ url: "/og.png", width: 1536, height: 1024, alt: "مشروع سهيل داخل Nawwsaj Innovation Lab" }] },
  twitter: { card: "summary_large_image", title: "Suhail سهيل | Nawwsaj Lab", description: "LoRa · Edge Systems · Embedded Hardware", images: ["/og.png"] },
};

export default function SuhailPage() {
  const structuredData = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "الرئيسية", item: "https://www.nawwsaj.com/" }, { "@type": "ListItem", position: 2, name: "Suhail سهيل", item: "https://www.nawwsaj.com/projects/suhail" }] };
  return <main className="suhail-page" dir="rtl"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} /><header className="project-header"><Link className="brand" href="/"><span className="brand-mark" aria-hidden="true">N</span><span>Nawwsaj <small>INNOVATION LAB</small></span></Link><Link href="/services">الخدمات</Link></header><section className="suhail-hero"><div className="suhail-copy"><p className="section-label">FLAGSHIP ENGINEERING PROJECT / 01</p><h1>Suhail <span>| سهيل</span></h1><p className="suhail-lead">منظومة اتصال ميداني مصممة للعمل في البيئات ذات الاتصال الضعيف أو المنقطع، قيد التطوير والاختبار داخل Nawwsaj Lab.</p><div className="project-tags"><span>LoRa</span><span>Edge Systems</span><span>Embedded Hardware</span><span>Offline Communication</span><span>Monitoring</span></div><p className="project-status"><i /> BUILD &amp; TEST PHASE</p></div><div className="suhail-system" aria-hidden="true"><div className="suhail-orbit orbit-one"/><div className="suhail-orbit orbit-two"/><div className="suhail-core">S<small>FIELD NODE</small></div><span className="node-label node-a">LORA / TX</span><span className="node-label node-b">EDGE / LOCAL</span><span className="node-label node-c">MONITOR / RX</span></div></section><section className="suhail-details"><div><p className="section-label">PROJECT CONTEXT</p><h2>اتصال محلي عندما لا تكون الشبكة خيارًا مضمونًا.</h2></div><div className="suhail-detail-grid"><article><span>01</span><h3>المشكلة</h3><p>الحاجة إلى تبادل معلومات ميدانية في مواقع قد يكون فيها اتصال الإنترنت ضعيفًا أو منقطعًا.</p></article><article><span>02</span><h3>التوجه الهندسي</h3><p>الجمع بين LoRa والأنظمة المضمنة والمعالجة الطرفية لبناء اتصال محلي قابل للاختبار.</p></article><article><span>03</span><h3>الحالة الحالية</h3><p>المشروع قيد التطوير والاختبار داخل المعمل. ستتوفر رحلة البناء والتوثيق هنا لاحقًا.</p></article></div><div className="actions"><Link className="button primary" href="/#start">ابدأ مشروعك</Link><Link className="button secondary" href="/">العودة إلى المعمل</Link></div></section></main>;
}
